# Generated by Django 5.0.3 on 2024-03-18 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('strength_max', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('body_max', models.IntegerField(default=0)),
                ('reaction', models.IntegerField(default=0)),
                ('reaction_max', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('intelligence_max', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
                ('willpower_max', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('charisma_max', models.IntegerField(default=0)),
                ('melee_reach', models.IntegerField(default=0)),
                ('movement_distance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_arms', models.IntegerField(default=0)),
                ('additional_legs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeltaDefence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soak_test_bonus_dice', models.IntegerField(default=0)),
                ('impact_armor', models.IntegerField(default=0)),
                ('ballistic_armor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('free_traits', models.IntegerField()),
                ('trait_with_drawback', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('official', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovementAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ground', 'Ground'), ('Air', 'Air'), ('Water', 'Water')], max_length=100)),
                ('on_all_four', models.BooleanField(default=False)),
                ('distance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dice_pool', models.CharField(choices=[('Brawn Pool', 'Brawn Pool'), ('Finesse Pool', 'Finesse Pool'), ('Focus Pool', 'Focus Pool'), ('Resolve Pool', 'Resolve Pool')], max_length=100)),
                ('skill_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.activeskillgroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeltaSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_dice', models.IntegerField(default=0)),
                ('modifier_dice', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.activeskill')),
            ],
        ),
        migrations.CreateModel(
            name='DeltaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeltaStats', to='characters.deltaattributes')),
                ('body', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeltaStats', to='characters.deltabody')),
                ('defence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeltaStats', to='characters.deltadefence')),
                ('skills', models.ManyToManyField(blank=True, to='characters.deltaskill')),
                ('movement_ability', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeltaStats', to='characters.movementability')),
            ],
        ),
        migrations.CreateModel(
            name='HeritageDrawback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('delta_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.deltastats')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.heritage')),
            ],
        ),
        migrations.CreateModel(
            name='HeritageTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('delta_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.deltastats')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.heritage')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.BooleanField(default=False)),
                ('strength', models.IntegerField(default=1)),
                ('body', models.IntegerField(default=1)),
                ('reaction', models.IntegerField(default=1)),
                ('intelligence', models.IntegerField(default=1)),
                ('willpower', models.IntegerField(default=1)),
                ('charisma', models.IntegerField(default=1)),
                ('zoetic_potential', models.IntegerField(default=6)),
                ('melee_reach_base', models.IntegerField(default=0)),
                ('movement_distance_base', models.IntegerField(default=6)),
                ('condition_physical', models.IntegerField(default=6)),
                ('condition_stun', models.IntegerField(default=6)),
                ('melee_weapons', models.IntegerField(default=0)),
                ('unarmed_combat', models.IntegerField(default=0)),
                ('martial_arts', models.IntegerField(default=0)),
                ('throwing_weapons', models.IntegerField(default=0)),
                ('cybertechtronic_combat', models.IntegerField(default=0)),
                ('athletics', models.IntegerField(default=0)),
                ('firearms', models.IntegerField(default=0)),
                ('gunnery', models.IntegerField(default=0)),
                ('heavy_weapons', models.IntegerField(default=0)),
                ('energy_weapons', models.IntegerField(default=0)),
                ('archery', models.IntegerField(default=0)),
                ('articulated_maneuvers', models.IntegerField(default=0)),
                ('shadow', models.IntegerField(default=0)),
                ('drive', models.IntegerField(default=0)),
                ('fly', models.IntegerField(default=0)),
                ('observation', models.IntegerField(default=0)),
                ('biotech', models.IntegerField(default=0)),
                ('reconnaissance', models.IntegerField(default=0)),
                ('locksmith', models.IntegerField(default=0)),
                ('computer_hacking', models.IntegerField(default=0)),
                ('computer_electronic_warfare', models.IntegerField(default=0)),
                ('computer_programming', models.IntegerField(default=0)),
                ('engineering_mechanical', models.IntegerField(default=0)),
                ('engineering_industrial', models.IntegerField(default=0)),
                ('engineering_aeronautics', models.IntegerField(default=0)),
                ('engineering_armory', models.IntegerField(default=0)),
                ('engineering_nautical', models.IntegerField(default=0)),
                ('artificing', models.IntegerField(default=0)),
                ('negotiations', models.IntegerField(default=0)),
                ('rituals', models.IntegerField(default=0)),
                ('channeling', models.IntegerField(default=0)),
                ('sorcery', models.IntegerField(default=0)),
                ('astral_senses', models.IntegerField(default=0)),
                ('survival', models.IntegerField(default=0)),
                ('conjuring', models.IntegerField(default=0)),
                ('leadership', models.IntegerField(default=0)),
                ('subterfuge', models.IntegerField(default=0)),
                ('coercion', models.IntegerField(default=0)),
                ('fascination', models.IntegerField(default=0)),
                ('corporate_etiquette', models.IntegerField(default=0)),
                ('street_etiquette', models.IntegerField(default=0)),
                ('civic_etiquette', models.IntegerField(default=0)),
                ('aristocratic_etiquette', models.IntegerField(default=0)),
                ('military_etiquette', models.IntegerField(default=0)),
                ('criminal_etiquette', models.IntegerField(default=0)),
                ('wasteland_etiquette', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('heritage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritage')),
                ('heritage_drawback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritagedrawback')),
                ('heritage_trait_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_1', to='characters.heritagetrait')),
                ('heritage_trait_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_2', to='characters.heritagetrait')),
                ('heritage_trait_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_3', to='characters.heritagetrait')),
                ('magic_ablity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.magicabilities')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.knowledgetopic')),
            ],
        ),
        migrations.CreateModel(
            name='UpliftedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attribute_cost', models.IntegerField(default=0)),
                ('small', models.BooleanField()),
                ('delta_stats', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.deltastats')),
                ('trait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritagetrait')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='uplifted_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.upliftedtype'),
        ),
    ]
