# Generated by Django 5.0.3 on 2024-03-11 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('free_traits', models.IntegerField()),
                ('trait_with_drawback', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UpliftedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='aristocratic_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='body',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='civic_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='corporate_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='criminal_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='military_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='reaction',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='street_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='wasteland_etiquette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='willpower',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='zoetic_potential',
            field=models.IntegerField(default=6),
        ),
        migrations.CreateModel(
            name='ActiveSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skill_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.activeskillgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkillValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.activeskills')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='heritage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritage'),
        ),
        migrations.CreateModel(
            name='HeritageDrawback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.heritage')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='heritage_drawback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritagedrawback'),
        ),
        migrations.CreateModel(
            name='HeritageTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='characters.heritage')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='heritage_trait_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_1', to='characters.heritagetrait'),
        ),
        migrations.AddField(
            model_name='character',
            name='heritage_trait_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_2', to='characters.heritagetrait'),
        ),
        migrations.AddField(
            model_name='character',
            name='heritage_trait_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heritage_trait_3', to='characters.heritagetrait'),
        ),
        migrations.AddField(
            model_name='character',
            name='magic_ablity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.magicabilities'),
        ),
        migrations.AddField(
            model_name='character',
            name='uplifted_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.upliftedtype'),
        ),
    ]
