# Generated by Django 5.0.3 on 2024-03-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_activeskillgroup_heritage_magicabilities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magicabilities',
            old_name='Name',
            new_name='name',
        ),
    ]
