# Generated by Django 5.0.3 on 2024-03-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_rename_name_magicabilities_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveSkills',
            new_name='ActiveSkill',
        ),
    ]
