# Generated by Django 5.0.3 on 2024-03-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_lifestyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='rent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
