# Generated by Django 5.0.3 on 2024-03-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_upliftedtype_attribute_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('strength_max', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('body_max', models.IntegerField(default=0)),
                ('reaction', models.IntegerField(default=0)),
                ('reaction_max', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('intelligence_max', models.IntegerField(default=0)),
                ('willpower', models.IntegerField(default=0)),
                ('willpower_max', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('charisma_max', models.IntegerField(default=0)),
            ],
        ),

    ]
