# Generated by Django 5.0.3 on 2024-03-12 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_deltaattributes_upliftedtype_delta_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftedtype',
            name='delta_attributes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='characters.deltaattributes'),
            preserve_default=False,
        ),
    ]
