# Generated by Django 5.0.3 on 2024-03-12 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_upliftedtype_delta_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_arms', models.IntegerField(default=0)),
                ('additional_legs', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='upliftedtype',
            name='trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.heritagetrait'),
        ),
        migrations.AlterField(
            model_name='upliftedtype',
            name='delta_attributes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_object', to='characters.deltaattributes'),
        ),
    ]
