# Generated by Django 5.0.3 on 2024-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_deltabody_upliftedtype_trait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftedtype',
            name='small',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
