# Generated by Django 5.0.3 on 2024-03-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_upliftedtype_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='upliftedtype',
            name='delta_body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_object', to='characters.deltabody'),
        ),
    ]
