# Generated by Django 5.0.3 on 2024-03-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_upliftedtype_delta_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
